### ISSUE TITLE
启动时可能会遇到的问题

### ISSUE THREAD

**Issue by zqs9810** [dongsuo/py_vislib#1]
按照方案一启动项目后，注册登录模块无问题，两个模块的均无法正常使用呢
1、查询表字段时，后端提示order_analysis表不存在
db.query(request.GET['sql'])
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'py_vislib.order_analysis' doesn't exist")
2、仪表盘面板也失败了
django.db.utils.ProgrammingError: (1146, "Table 'py_vislib.vislib_dashboard' doesn't exist")

应该是缺少一部分数据库表呢，是我的操作有问题吗~  @dongsuo 可以排查一下哦

**Comment by zqs9810** [comment]
这是当前数据库中的所有表
auth_group, 
auth_group_permissions, 
auth_permission, 
auth_user, 
auth_user_groups, 
auth_user_user_permissions,
 django_admin_log,
 django_content_type,
 django_migrations, 
django_session

**Comment by dongsuo** [comment]
好的，谢谢反馈

**Comment by zqs9810** [comment]
嘿嘿,star一个等更新~

**Comment by zqs9810** [comment]
问题得以解决~
在IDE执行配置开发数据库指令：
python manage.py makemigrations vislib  --settings=py_vislib.settings.local
python manage.py migrate  --settings=py_vislib.settings.local
相关数据库表，Django 就会给建好啦

PS：启动项目时导入测试分析数据：
将下方数据导入到本地的测试数据库中，并将 `/vislib/views.py` 文件中 `execSql` 方法中的数据库连接方式改成对应的数据库配置。
[vue-data-board_test_data.sql](https://www.yuque.com/attachments/yuque/0/2020/sql/192008/1585748462999-90e27e47-ec12-48e6-a15a-c95ef5dec7b3.sql)

详见：[如何启动项目](https://docs.vislib.best/kqqi2k.html)

**Comment by Traclor** [comment]
按方案一启动（我是下载的ZIP）
A.pip install django-cors-headers
![65a57580d356cf58](https://user-images.githubusercontent.com/45586179/81471460-d7c8e780-9223-11ea-955b-d6b587bab943.png)
B.pip install mysqlclient
![52d0036c08e452](https://user-images.githubusercontent.com/45586179/81471479-fd55f100-9223-11ea-8fe5-3b7a66ae7d91.png)
C.修改数据库配置
![42db71a438990f48](https://user-images.githubusercontent.com/45586179/81471525-41e18c80-9224-11ea-8823-0e98098be57a.png)
D.配置开发数据库
        1.python manage.py makemigrations --settings=py_vislib.settings.local
![53f42d47363d0519](https://user-images.githubusercontent.com/45586179/81471579-a7ce1400-9224-11ea-9543-a2f3995b7863.png)
         2.python manage.py makemigrations --settings=py_vislib.settings.local（我这里python3命令无法识别 我是win10）
![66b112d7c124e003](https://user-images.githubusercontent.com/45586179/81471956-80c51180-9227-11ea-86dc-b889a8df3983.png)
          3.python manage.py migrate --settings=py_vislib.settings.local
![-3fc91958922b4d03](https://user-images.githubusercontent.com/45586179/81471995-c8e43400-9227-11ea-80ae-d7aa570d7a45.png)
![1d44d4249dfa9169](https://user-images.githubusercontent.com/45586179/81472008-e0232180-9227-11ea-94c2-c031422f9fbc.png)
E.配置数据源数据库
![-7fbe8f722a3c3b47](https://user-images.githubusercontent.com/45586179/81472085-398b5080-9228-11ea-84c4-68519e22f982.png)
F.启动项目
python manage.py runserver --settings=py_vislib.settings.local
![-495f3378d44700b5](https://user-images.githubusercontent.com/45586179/81472141-925ae900-9228-11ea-9288-d98938cf9761.png)
![-4df57d6eb99b3ccc](https://user-images.githubusercontent.com/45586179/81472579-a7854700-922b-11ea-8838-dd321f5e41b4.png)
![63664b0d58f2c030](https://user-images.githubusercontent.com/45586179/81472582-aa803780-922b-11ea-9e07-f8fe4a572e3e.png)
无法连接后端

**Comment by Traclor** [comment]
> 按方案一启动（我是下载的ZIP）
> A.pip install django-cors-headers
> ![65a57580d356cf58](https://user-images.githubusercontent.com/45586179/81471460-d7c8e780-9223-11ea-955b-d6b587bab943.png)
> B.pip install mysqlclient
> ![52d0036c08e452](https://user-images.githubusercontent.com/45586179/81471479-fd55f100-9223-11ea-8fe5-3b7a66ae7d91.png)
> C.修改数据库配置
> ![42db71a438990f48](https://user-images.githubusercontent.com/45586179/81471525-41e18c80-9224-11ea-8823-0e98098be57a.png)
> D.配置开发数据库
> 1.python manage.py makemigrations --settings=py_vislib.settings.local
> ![53f42d47363d0519](https://user-images.githubusercontent.com/45586179/81471579-a7ce1400-9224-11ea-9543-a2f3995b7863.png)
> 2.python manage.py makemigrations --settings=py_vislib.settings.local（我这里python3命令无法识别 我是win10）
> ![66b112d7c124e003](https://user-images.githubusercontent.com/45586179/81471956-80c51180-9227-11ea-86dc-b889a8df3983.png)
> 3.python manage.py migrate --settings=py_vislib.settings.local
> ![-3fc91958922b4d03](https://user-images.githubusercontent.com/45586179/81471995-c8e43400-9227-11ea-80ae-d7aa570d7a45.png)
> ![1d44d4249dfa9169](https://user-images.githubusercontent.com/45586179/81472008-e0232180-9227-11ea-94c2-c031422f9fbc.png)
> E.配置数据源数据库
> ![-7fbe8f722a3c3b47](https://user-images.githubusercontent.com/45586179/81472085-398b5080-9228-11ea-84c4-68519e22f982.png)
> F.启动项目
> python manage.py runserver --settings=py_vislib.settings.local
> ![-495f3378d44700b5](https://user-images.githubusercontent.com/45586179/81472141-925ae900-9228-11ea-9288-d98938cf9761.png)
> ![-4df57d6eb99b3ccc](https://user-images.githubusercontent.com/45586179/81472579-a7854700-922b-11ea-8838-dd321f5e41b4.png)
> ![63664b0d58f2c030](https://user-images.githubusercontent.com/45586179/81472582-aa803780-922b-11ea-9e07-f8fe4a572e3e.png)
> 无法连接后端

![3e8f7c410d23c650](https://user-images.githubusercontent.com/45586179/81473002-66426680-922e-11ea-983c-ec75b5992a3d.png)
这是我的python版本号
