### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Traclor** [dongsuo/py_vislib#3]
3按方案一启动（我是下载的ZIP）
> A.pip install django-cors-headers
> ![65a57580d356cf58](https://user-images.githubusercontent.com/45586179/81471460-d7c8e780-9223-11ea-955b-d6b587bab943.png)
> B.pip install mysqlclient
> ![52d0036c08e452](https://user-images.githubusercontent.com/45586179/81471479-fd55f100-9223-11ea-8fe5-3b7a66ae7d91.png)
> C.修改数据库配置
> ![42db71a438990f48](https://user-images.githubusercontent.com/45586179/81471525-41e18c80-9224-11ea-8823-0e98098be57a.png)
> D.配置开发数据库
> 1.python manage.py makemigrations --settings=py_vislib.settings.local
> ![53f42d47363d0519](https://user-images.githubusercontent.com/45586179/81471579-a7ce1400-9224-11ea-9543-a2f3995b7863.png)
> 2.python manage.py makemigrations --settings=py_vislib.settings.local（我这里python3命令无法识别 我是win10）
> ![66b112d7c124e003](https://user-images.githubusercontent.com/45586179/81471956-80c51180-9227-11ea-86dc-b889a8df3983.png)
> 3.python manage.py migrate --settings=py_vislib.settings.local
> ![-3fc91958922b4d03](https://user-images.githubusercontent.com/45586179/81471995-c8e43400-9227-11ea-80ae-d7aa570d7a45.png)
> ![1d44d4249dfa9169](https://user-images.githubusercontent.com/45586179/81472008-e0232180-9227-11ea-94c2-c031422f9fbc.png)
> E.配置数据源数据库
> ![-7fbe8f722a3c3b47](https://user-images.githubusercontent.com/45586179/81472085-398b5080-9228-11ea-84c4-68519e22f982.png)
> F.启动项目
> python manage.py runserver --settings=py_vislib.settings.local
> ![-495f3378d44700b5](https://user-images.githubusercontent.com/45586179/81472141-925ae900-9228-11ea-9288-d98938cf9761.png)
> ![-4df57d6eb99b3ccc](https://user-images.githubusercontent.com/45586179/81472579-a7854700-922b-11ea-8838-dd321f5e41b4.png)
> ![63664b0d58f2c030](https://user-images.githubusercontent.com/45586179/81472582-aa803780-922b-11ea-9e07-f8fe4a572e3e.png)
> 无法连接后端

![3e8f7c410d23c650](https://user-images.githubusercontent.com/45586179/81473002-66426680-922e-11ea-983c-ec75b5992a3d.png)
这是我的python版本号

这是在注册页面信息输完后点击注册报的错
![22a0d36ffe1bc91c](https://user-images.githubusercontent.com/45586179/81474973-9e03db00-923b-11ea-928a-ff457f473cf3.png)

按理说post应该是8000(服务器端口)但是却是8080（前端端口），后端启动的默认端口

**Comment by Traclor** [comment]
问题解决了，在前端的env设置的时候添加了本地服务器的地址，然后设置了跨域访问，然后出现新问题是无法访问测试数据
![-255f01cdad3eff3](https://user-images.githubusercontent.com/45586179/81495226-651e4180-92e1-11ea-899e-5890bc79fe2a.png)

**Comment by xianzhiyun** [comment]
可以正常注册
/login 正常返回信息
/userInfo 获取不到信息，request.user.is_authenticated 一直为false，没有找到解决办法
